modLoader="javafml"
loaderVersion="[26.2,)"
license="LGPL-3.0-only"

[[mods]]
modId="hyperion"
version="1.0.0"
displayName="Hyperion Optimizer"
description='''High-Performance Cross-Platform Minecraft Optimization Engine.'''
authors="Hyperion Team"

[[dependencies.hyperion]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hyperion]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,27.0)"
    ordering="NONE"
    side="BOTH"
