modLoader="javafml"
loaderVersion="[26.2,)"
license="MIT"

[[mods]]
modId="hyperion_optimizer"
version="1.0.3"
displayName="Hyperion Optimizer"
description='''High-Performance Cross-Platform Minecraft Optimization Engine.'''
authors="Hyperion Team"
logoFile="icon.png"
issueTrackerURL="https://github.com/qefwgrhgj/hyperion-optimizer/issues"
displayURL="https://github.com/qefwgrhgj/hyperion-optimizer"

[[dependencies.hyperion_optimizer]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hyperion_optimizer]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,27.0)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
config = "hyperion.mixins.json"
