modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="hyperion_optimizer"
version="1.0.3"
displayName="Hyperion Optimizer"
description='''High-Performance Sovereign Multi-Core Cross-Platform Minecraft Optimization Engine.'''
authors="Hyperion Team"
logoFile="icon.png"
issueTrackerURL="https://github.com/qefwgrhgj/hyperion-optimizer/issues"
displayURL="https://github.com/qefwgrhgj/hyperion-optimizer"

[[dependencies.hyperion_optimizer]]
    modId="forge"
    type="required"
    versionRange="[37.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hyperion_optimizer]]
    modId="minecraft"
    type="required"
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
config = "hyperion.mixins.json"
