plugins {
    id "java-library"
}

dependencies {
    // Platform-independent core libraries (Netty, FastUtil, Gson, LWJGL bindings)
    compileOnly "com.google.code.gson:gson:2.10.1"
    compileOnly "it.unimi.dsi:fastutil:8.5.12"
    compileOnly "org.lwjgl:lwjgl:3.3.3"
    compileOnly "org.lwjgl:lwjgl-opengl:3.3.3"
    compileOnly "io.netty:netty-all:4.1.97.Final"
}

java {
    withSourcesJar()
}
